require 'jekyll'

module Jekyll
  # Jekyll hook that injects utility bar HTML after all processing is complete
  # This ensures the HTML is not processed by Pandoc
  Jekyll::Hooks.register :pages, :post_render do |page|
    # Only process markdown pages that use the lesson-layout
    next unless page.is_a?(Jekyll::Page)
    next unless page.ext == '.md' || page.ext == '.markdown'
    next unless page.data['layout'] == 'lesson-layout'
    
    # Check if output contains utility bar placeholder
    next unless page.output.include?('<!-- UTILITY_BAR_PLACEHOLDER -->')
    
    # Create utility bar HTML
    utility_bar_html = <<~HTML
      <div class="utility-bar">
        <div class="utility-bar-toc">
          <!-- TOC buttons will be generated by JavaScript -->
        </div>
        <div class="utility-bar-content">
          <button class="button is-small" id="focus-button">Focus</button>
        </div>
      </div>
    HTML
    
    # Replace the placeholder with the actual utility bar HTML
    page.output = page.output.gsub('<!-- UTILITY_BAR_PLACEHOLDER -->', utility_bar_html)
  end
end

