require 'jekyll'

module Jekyll
  # Utility bar tag - outputs the utility bar HTML directly
  class UtilityBarTag < Liquid::Tag
    def render(context)
      <<~HTML
        <div class="utility-bar">
          <div class="utility-bar-toc">
            <!-- TOC buttons will be generated by JavaScript -->
          </div>
          <div class="utility-bar-content">
            <button class="button is-small" id="focus-button">Focus</button>
          </div>
        </div>
      HTML
    end
  end
end

Liquid::Template.register_tag('utility_bar', Jekyll::UtilityBarTag)
